import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { execFileSync } from 'node:child_process';
import { afterEach, describe, expect, it } from 'vitest';
import {
  collectProposalContext,
  collectRepositoryPolicyDiff,
  createProposalDirectory,
  prepareQuarantineRoot,
  snapshotRepository,
} from '../src/proposal-io.js';

const cleanup: string[] = [];

function repo(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bce-proposal-'));
  cleanup.push(root);
  execFileSync('git', ['init', '-q', '-b', 'main', root]);
  fs.mkdirSync(path.join(root, 'docs'), { recursive: true });
  fs.mkdirSync(path.join(root, 'src'), { recursive: true });
  fs.writeFileSync(path.join(root, 'docs', 'intent.md'), 'Keep provider calls behind the gateway.\n');
  fs.writeFileSync(path.join(root, 'src', 'index.ts'), 'export const value = 1;\n');
  fs.writeFileSync(path.join(root, '.env'), 'TOKEN=must-not-leak\n');
  execFileSync('git', ['-C', root, 'add', 'docs/intent.md', 'src/index.ts']);
  execFileSync('git', ['-C', root, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'fixture']);
  return root;
}

afterEach(() => {
  for (const dir of cleanup.splice(0)) fs.rmSync(dir, { recursive: true, force: true });
});

describe('proposal context I/O boundary', () => {
  it('is deterministic, bounded, and excludes ignored or secret-like files', () => {
    const root = repo();
    const first = collectProposalContext({ repoDir: root, intentFile: 'docs/intent.md' });
    const second = collectProposalContext({ repoDir: root, intentFile: 'docs/intent.md' });
    expect(first).toEqual(second);
    expect(first.files.map((entry) => entry.path)).toEqual(['src/index.ts']);
    expect(stable(first)).not.toContain('must-not-leak');
    expect(first.authoritativeIntentRefs[0]?.ref).toBe('docs/intent.md');
  });

  it('records budget exclusions instead of silently truncating files', () => {
    const root = repo();
    fs.writeFileSync(path.join(root, 'src', 'second.ts'), 'export const second = 2;\n');
    const context = collectProposalContext({ repoDir: root, intentFile: 'docs/intent.md', maxFiles: 1 });
    expect(context.files).toHaveLength(1);
    expect(context.excluded.classes).toContain('context-budget');
    expect(context.excluded.paths).toContain('src/second.ts');
  });

  it('keeps the remote host in repository identity and hashes ignored non-generated bytes', () => {
    const root = repo();
    execFileSync('git', ['-C', root, 'remote', 'add', 'origin', 'git@gitlab.example:group/repo.git']);
    const before = snapshotRepository(root);
    expect(before.identity).toBe('gitlab.example/group/repo');
    fs.writeFileSync(path.join(root, '.gitignore'), 'ignored.ts\n');
    execFileSync('git', ['-C', root, 'add', '.gitignore']);
    execFileSync('git', ['-C', root, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'ignore fixture']);
    const clean = snapshotRepository(root);
    fs.writeFileSync(path.join(root, 'ignored.ts'), 'export const ignored = true;\n');
    expect(snapshotRepository(root).worktreeDigest).not.toBe(clean.worktreeDigest);
  });

  it('captures protected changes from the remote-base revision', () => {
    const root = repo();
    fs.mkdirSync(path.join(root, '.github'), { recursive: true });
    fs.writeFileSync(path.join(root, '.github', 'CODEOWNERS'), '*.ts @security\n');
    execFileSync('git', ['-C', root, 'add', '.github/CODEOWNERS']);
    execFileSync('git', ['-C', root, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'policy base']);
    const base = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
    execFileSync('git', ['-C', root, 'update-ref', 'refs/remotes/origin/main', base]);
    fs.writeFileSync(path.join(root, '.github', 'CODEOWNERS'), '*.ts @everyone\n');
    expect(collectRepositoryPolicyDiff(root)).toEqual({
      baseRef: 'main',
      baseHeadRevision: base,
      baseRevision: base,
      complete: true,
      files: [{ path: '.github/CODEOWNERS', before: '*.ts @security\n', after: '*.ts @everyone\n' }],
    });
    expect(collectRepositoryPolicyDiff(root, { baseRef: 'main', baseHeadRevision: base })).toEqual({
      baseRef: 'main',
      baseHeadRevision: base,
      baseRevision: base,
      complete: true,
      files: [{ path: '.github/CODEOWNERS', before: '*.ts @security\n', after: '*.ts @everyone\n' }],
    });
    execFileSync('git', ['-C', root, 'add', '.github/CODEOWNERS']);
    execFileSync('git', ['-C', root, '-c', 'user.name=Test', '-c', 'user.email=test@example.com', 'commit', '-qm', 'advance base']);
    execFileSync('git', ['-C', root, 'update-ref', 'refs/remotes/origin/main', 'HEAD']);
    expect(collectRepositoryPolicyDiff(root, { baseRef: 'main', baseHeadRevision: base })).toEqual({
      baseRef: null, baseHeadRevision: null, baseRevision: null, complete: false, files: [],
    });
  });

  it('cannot hide protected deletion by renaming an evaluator to an unprotected path', () => {
    const root = repo();
    const base = execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
    execFileSync('git', ['-C', root, 'update-ref', 'refs/remotes/origin/main', base]);
    fs.mkdirSync(path.join(root, 'lib'));
    execFileSync('git', ['-C', root, 'mv', 'src/index.ts', 'lib/unprotected.ts']);
    expect(collectRepositoryPolicyDiff(root)).toEqual({
      baseRef: 'main',
      baseHeadRevision: base,
      baseRevision: base,
      complete: true,
      files: [{ path: 'src/index.ts', before: 'export const value = 1;\n' }],
    });
  });

  it('refuses traversal, governed-directory overlap, and symlink escapes', () => {
    const root = repo();
    expect(() => prepareQuarantineRoot({ repoDir: root, out: '../outside' })).toThrow(/escapes/);
    expect(() => prepareQuarantineRoot({ repoDir: root, out: '.blueprints/proposals' })).toThrow(/governed/);
    expect(() => prepareQuarantineRoot({ repoDir: root, out: '.' })).toThrow(/escapes/);
    expect(() => prepareQuarantineRoot({ repoDir: root, out: 'C:\\outside' })).toThrow(/repository-relative/);
    expect(() => prepareQuarantineRoot({ repoDir: root, out: '\\\\server\\share' })).toThrow(/repository-relative/);

    const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'bce-outside-'));
    cleanup.push(outside);
    fs.symlinkSync(outside, path.join(root, 'linked'));
    expect(() => prepareQuarantineRoot({ repoDir: root, out: 'linked/proposals' })).toThrow(/symbolic link/);
  });

  it('creates safe, non-overwriting proposal leaves', () => {
    const root = repo();
    const quarantine = prepareQuarantineRoot({ repoDir: root, out: '.bce/proposals' });
    const created = createProposalDirectory(quarantine, 'gateway-boundary');
    expect(fs.existsSync(created)).toBe(true);
    expect(() => createProposalDirectory(quarantine, 'gateway-boundary')).toThrow(/already exists/);
    expect(() => createProposalDirectory(quarantine, '../escape')).toThrow(/kebab-case/);
  });

  it('refuses an intent symlink that resolves outside the repository', () => {
    const root = repo();
    const outside = path.join(os.tmpdir(), `bce-secret-${process.pid}.txt`);
    fs.writeFileSync(outside, 'secret');
    cleanup.push(outside);
    fs.symlinkSync(outside, path.join(root, 'docs', 'outside.md'));
    expect(() => collectProposalContext({ repoDir: root, intentFile: 'docs/outside.md' })).toThrow(/outside --repo/);
  });
});

function stable(value: unknown): string {
  return JSON.stringify(value);
}
