import fs from 'node:fs';
import path from 'node:path';
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function loadFilms(root) {
  const catalog=JSON.parse(fs.readFileSync(path.join(root,'assets/films/catalog.json'),'utf8'));
  const prefix=`https://github.com/blueprint-conformance/bce/releases/download/${catalog.release}/`;
  if(catalog.schemaVersion!==1||!/^media-\d{4}-\d{2}-\d{2}$/.test(catalog.release)||catalog.mediaBase!==prefix||!Array.isArray(catalog.films)||!catalog.films.length)throw new Error('Invalid film catalog');
  const media=JSON.parse(fs.readFileSync(path.join(root,'assets/films/media-assets.json'),'utf8'));
  if(media.release!==catalog.release||!Array.isArray(media.assets))throw new Error('Media release identity mismatch');
  const assets=new Map(media.assets.map(a=>[a.file,a]));
  if(assets.size!==media.assets.length)throw new Error('Duplicate media asset');
  const ids=new Set();for(const f of catalog.films){
    if(!/^[a-z][a-z0-9-]+$/.test(f.id)||ids.has(f.id)||!f.title||!f.description||!f.boundary||!f.collection||!Number.isFinite(f.duration)||f.duration<=0||!Number.isInteger(f.bytes)||f.bytes<=0||!Number.isInteger(f.width)||f.width<1||!Number.isInteger(f.height)||f.height<1||!/^[a-f0-9]{64}$/.test(f.sha256)||f.video!==prefix+f.id+'.mp4'||f.poster!==prefix+f.id+'.jpg'||f.captions!==f.id+'.vtt'||!['summary','walkthrough'].includes(f.textKind)||!Array.isArray(f.transcript)||!f.transcript.length)throw new Error('Invalid film record: '+f.id);
    const original=assets.get(f.id+'.mp4');if(original?.sha256!==f.sha256||original.bytes!==f.bytes||!assets.has(f.id+'.jpg'))throw new Error('Film and media manifest disagree: '+f.id);
    ids.add(f.id);if(!fs.readFileSync(path.join(root,'assets/films',f.captions),'utf8').startsWith('WEBVTT\n'))throw new Error('Missing film captions: '+f.id);
    for(const c of f.transcript)if(!Number.isFinite(c.start)||!Number.isFinite(c.end)||c.start<0||c.end>f.duration+.1||c.end<=c.start||typeof c.text!=='string'||!c.text)throw new Error('Invalid film transcript: '+f.id);
  }
  if(!ids.has(catalog.featured))throw new Error('Featured film is absent');return catalog;
}
const duration=s=>`${Math.floor(s/60)}:${String(Math.round(s%60)).padStart(2,'0')}`;
function video(f,base){return `<video controls playsinline preload="none" poster="${escape(f.poster)}" width="${f.width}" height="${f.height}" aria-label="${escape(f.title)}"><source src="${escape(f.video)}" type="video/mp4">${f.textKind==='walkthrough'?`<track kind="descriptions" src="${base}${f.captions}" srclang="en" label="English visual description">`:''}<p><a href="${escape(f.video)}">Download ${escape(f.title)}</a></p></video>`;}
export function filmFeature(catalog){const f=catalog.films.find(f=>f.id===catalog.featured);return `<section class="film-feature" aria-labelledby="watch-the-context-move"><div class="film-feature-copy"><p class="film-kicker">WATCH THE MECHANISM</p><h2 id="watch-the-context-move">Context at every scale.</h2><p>Follow the boundary from system intent to code. Watch context narrow, a finding trigger repair, and evidence return for review.</p><p class="film-boundary">${escape(f.boundary)}</p><div class="film-actions"><a class="film-primary" href="assets/films/context-spectrum/index.html">Explore the 3D loop ↗</a><a href="films/">Browse all ${catalog.films.length} films →</a></div></div><figure>${video(f,'assets/films/')}<figcaption>90 seconds · C1–C4 architecture views · silent · text walkthrough available</figcaption></figure></section>`;}
export function filmLibrary(catalog){return `<div class="film-library"><section class="film-library-intro"><p class="film-kicker">THE MOVING ARCHITECTURE COLLECTION</p><h1 id="film-library">Watch the ideas take shape.</h1><p>Start with the context spectrum, follow the full architecture, or revisit the earlier agent films. Each clip keeps its original meaning and a permanent download.</p><div class="film-actions"><a class="film-primary" href="../assets/films/context-spectrum/index.html">Explore C1–C4 in 3D ↗</a><a href="../assets/films/catalog.json">Download the catalog</a></div><p class="film-boundary">C1–C4 here means architectural zoom levels, not the similarly named BCE constraint types. Reference designs and historical agent-product demonstrations do not establish released BCE capabilities.</p></section><nav class="film-collection-nav" aria-label="Film collections">${[...new Set(catalog.films.map(f=>f.collection))].map((c,i)=>`<a href="#collection-${i}">${escape(c)}</a>`).join('')}</nav>${[...new Set(catalog.films.map(f=>f.collection))].map((collection,i)=>`<section class="film-collection" aria-labelledby="collection-${i}"><h2 id="collection-${i}">${escape(collection)}</h2>${catalog.films.filter(f=>f.collection===collection).map(f=>`<article class="film-entry" id="${f.id}"><div class="film-screen">${video(f,'../assets/films/')}</div><div class="film-description"><p class="film-kicker">${duration(f.duration)} · ${f.width} × ${f.height}</p><h3>${escape(f.title)}</h3><p>${escape(f.description)}</p><p class="film-boundary">${escape(f.boundary)}</p><div class="film-actions"><a href="${escape(f.video)}" download>Download MP4 · ${(f.bytes/1048576).toFixed(1)} MB</a>${f.id===catalog.featured?'<a href="../assets/films/context-spectrum/index.html">Explore in 3D ↗</a>':''}</div><details><summary>${f.textKind==='walkthrough'?'Read the walkthrough':'Read the summary'}</summary><ol class="film-transcript">${f.transcript.map(c=>`<li><span>${duration(c.start)}</span><p>${escape(c.text)}</p></li>`).join('')}</ol><p class="film-digest">SHA-256 <code>${f.sha256}</code></p></details></div></article>`).join('')}</section>`).join('')}<section class="film-preservation"><h2 id="preserved">Kept as part of the project.</h2><p>Original films are stored in a dated media release. The checked-in catalog records each file’s identity, dimensions, duration and SHA-256 digest. Alternate cuts remain available even when the featured film changes.</p><a href="https://github.com/blueprint-conformance/bce/releases/tag/${catalog.release}">Open the media release ↗</a><p>For current engine behavior, use the <a href="../guides/quickstart/">quickstart</a> and <a href="../trust/">published evidence</a>.</p></section></div>`;}
export function publishFilmFiles(root,out){fs.cpSync(path.join(root,'assets/films'),path.join(out,'assets/films'),{recursive:true});}
