#!/usr/bin/env node
/**
 * gen-badges.mjs — the README's shields are GENERATED from ground truth, never typed.
 *
 * WHY THIS EXISTS. A badge is a claim rendered as a fact. The usual failure is not that a
 * badge is wrong on the day it is added — it is that the tree moves and the badge does not,
 * so "tests 412" sits on the front page of a repository that now has a different number, and
 * nothing anywhere reds. That is the same class `scripts/hero-demo-record.mjs` exists to kill
 * for the terminal block, applied to the row of shields above it.
 *
 * So no badge here carries a literal. Each one names a GROUND TRUTH FUNCTION that re-derives
 * its value from the tree — the test count from `vitest list`, the licence from package.json
 * cross-checked against the LICENSE file, the Node floor from .nvmrc cross-checked against
 * every workflow that pins one — and the badge is drawn from whatever that function returns.
 * A value that cannot be derived is a REFUSAL, not a default: a badge nobody can re-derive is
 * exactly the badge that will one day be quietly false.
 *
 * `--check` re-derives every value and diffs the drawn bytes against what is committed, so
 * drift is a red check rather than a discovery. That is the mode CI runs.
 *
 * EXTERNAL BADGE SERVICES ARE NOT USED, deliberately. A shields.io URL is a network
 * dependency on the one page that is supposed to demonstrate supply-chain discipline, it
 * renders nothing when the service is down or blocked, and — the part that matters here — it
 * is rendered from a value in a URL that no check in this repository can verify. A committed
 * SVG generated by this script is diffable, offline, and re-derivable.
 *
 * Zero dependencies. The only child process is the test runner, and only for the test count.
 *
 * Usage:
 *   node scripts/gen-badges.mjs             # re-derive and write assets/badges/*.svg
 *   node scripts/gen-badges.mjs --check     # re-derive and require the committed bytes to match
 *
 * Exit codes:
 *   0 — written, or (--check) every badge matches its ground truth.
 *   1 — (--check) drift: a committed badge no longer matches what the tree says.
 *   2 — harness failure (a ground truth could not be derived, or two sources disagree).
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const badgeDir = path.join(repoRoot, 'assets', 'badges');

function harness(msg) {
  console.error(`gen-badges: ${msg}`);
  process.exit(2);
}

const read = (rel) => {
  const p = path.join(repoRoot, rel);
  if (!existsSync(p)) harness(`${rel} is missing — this generator derives a badge value from it`);
  return readFileSync(p, 'utf8');
};

// ---------------------------------------------------------------------------
// Ground truth. Each function returns the badge's value or calls harness().
// Nothing here accepts a fallback: an underivable value is a refusal.
// ---------------------------------------------------------------------------

/**
 * The test count, from the runner's own enumeration rather than a grep for `it(`.
 * `vitest list` prints one fully-qualified test name per line — the same set `vitest run`
 * would execute — so the number on the badge is the number that actually runs.
 */
export function groundTruthTests() {
  let out;
  try {
    out = execFileSync('npx', ['vitest', 'list'], {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
      maxBuffer: 32 * 1024 * 1024,
    });
  } catch (e) {
    harness(`could not enumerate tests via \`vitest list\`: ${e.message}`);
  }
  const lines = out.split('\n').map((l) => l.trim()).filter((l) => l.includes(' > '));
  if (lines.length === 0) harness('`vitest list` enumerated no tests — refusing to draw a "0 tests" badge');
  return String(lines.length);
}

/**
 * The licence, from package.json — but only after the LICENSE file is confirmed to be the
 * same licence. A package.json field alone is a string anybody can edit; the pair agreeing
 * is what makes the badge worth anything.
 */
export function groundTruthLicense() {
  const declared = JSON.parse(read('package.json')).license;
  if (typeof declared !== 'string' || declared.length === 0) harness('package.json declares no license');
  const body = read('LICENSE');
  const wants = { 'Apache-2.0': /Apache License\s+Version 2\.0/ };
  const probe = wants[declared];
  if (!probe) harness(`no LICENSE cross-check is defined for the declared license "${declared}" — add one rather than trusting the field alone`);
  if (!probe.test(body)) harness(`package.json says ${declared} but LICENSE does not read as that licence`);
  return declared;
}

/**
 * The Node floor, from .nvmrc — cross-checked against every workflow that pins a version.
 * package.json carries no `engines` field in this tree, so .nvmrc plus the workflow pins ARE
 * the ground truth; if a workflow ever disagrees with .nvmrc, the badge refuses rather than
 * picking a winner.
 */
export function groundTruthNode() {
  const nvmrc = read('.nvmrc').trim();
  if (!/^\d+$/.test(nvmrc)) harness(`.nvmrc is "${nvmrc}", which is not a bare major version`);

  const wfDir = path.join(repoRoot, '.github', 'workflows');
  if (!existsSync(wfDir)) harness('.github/workflows is missing — the Node pin cannot be cross-checked');
  const disagree = [];
  let seen = 0;
  for (const f of readdirSync(wfDir).filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))) {
    const text = readFileSync(path.join(wfDir, f), 'utf8');
    for (const m of text.matchAll(/^\s*node-version:\s*'?"?(\d+)/gm)) {
      seen += 1;
      if (m[1] !== nvmrc) disagree.push(`${f} pins node ${m[1]}`);
    }
  }
  if (seen === 0) harness('no workflow pins a node-version — .nvmrc alone would be an unchecked claim');
  if (disagree.length) harness(`.nvmrc says ${nvmrc} but ${disagree.join('; ')}`);
  return `>=${nvmrc}`;
}

/**
 * "zero-dep" for the docs/proof tooling — asserted, not asserted-in-prose. The claim is that
 * the documentation site and the evidence verifier run with nothing installed, so the check is
 * that their sources import only `node:` builtins. A relative import is fine (it is still this
 * tree); a bare package specifier is not.
 */
export function groundTruthZeroDepDocs() {
  const guarded = ['scripts/build-docs-site.mjs', 'tools/verify-chain.mjs'];
  for (const rel of guarded) {
    const src = read(rel);
    for (const m of src.matchAll(/^\s*import\s+(?:[\s\S]*?\s+from\s+)?['"]([^'"]+)['"]/gm)) {
      const spec = m[1];
      const isBuiltin = spec.startsWith('node:');
      const isRelative = spec.startsWith('./') || spec.startsWith('../');
      if (!isBuiltin && !isRelative) {
        harness(`${rel} imports "${spec}" — the zero-dep docs badge would be false`);
      }
    }
  }
  return 'zero-dep';
}

/**
 * The three surfaces an agent can reach the engine through. Each is proven by the artifact
 * that provides it: two bin entries in package.json, and the composite action at the root.
 */
export function groundTruthAnyAgent() {
  const pkg = JSON.parse(read('package.json'));
  const bin = pkg.bin ?? {};
  const missing = [];
  if (!bin.bce) missing.push('CLI (package.json bin.bce)');
  if (!bin['bce-mcp']) missing.push('MCP (package.json bin.bce-mcp)');
  if (!existsSync(path.join(repoRoot, 'action.yml'))) missing.push('Action (action.yml)');
  if (missing.length) harness(`the "any agent" badge claims a surface this tree does not ship: ${missing.join(', ')}`);
  return 'CLI · Action · MCP';
}

// ---------------------------------------------------------------------------
// Drawing. Flat two-tone plate, self-contained like assets/bce-banner.svg — it
// owns its background so it reads the same on the light and dark themes.
//
// Width comes from a fixed advance, and the text is then pinned to exactly that
// width with textLength/lengthAdjust. That is what makes these deterministic:
// the badge does not depend on the renderer resolving the same font the author
// had, which is the usual reason a hand-drawn SVG badge looks broken elsewhere.
// ---------------------------------------------------------------------------
const FONT = 'ui-sans-serif, -apple-system, Segoe UI, Helvetica, Arial, sans-serif';
const FONT_SIZE = 11;
const ADVANCE = 6.4;   // px per character at 11px, for the reserved run
const PAD = 9;         // px of breathing room either side of a run
const HEIGHT = 20;

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function drawBadge({ label, value, valueFill }) {
  const labelRun = Math.round(label.length * ADVANCE);
  const valueRun = Math.round(value.length * ADVANCE);
  const labelW = labelRun + PAD * 2;
  const valueW = valueRun + PAD * 2;
  const total = labelW + valueW;
  const alt = `${label}: ${value}`;

  // Two rects and two runs. No gradients, no filters — a badge is 20px tall and
  // any of that would only cost bytes.
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${total}" height="${HEIGHT}" viewBox="0 0 ${total} ${HEIGHT}" role="img" aria-label="${esc(alt)}">
  <title>${esc(alt)}</title>
  <rect width="${total}" height="${HEIGHT}" rx="3" fill="#30363D"/>
  <path d="M${labelW} 0h${valueW - 3}a3 3 0 0 1 3 3v${HEIGHT - 6}a3 3 0 0 1-3 3h-${valueW - 3}z" fill="${valueFill}"/>
  <g font-family="${FONT}" font-size="${FONT_SIZE}" font-weight="500">
    <text x="${PAD}" y="14" textLength="${labelRun}" lengthAdjust="spacingAndGlyphs" fill="#C9D5E1">${esc(label)}</text>
    <text x="${labelW + PAD}" y="14" textLength="${valueRun}" lengthAdjust="spacingAndGlyphs" fill="#FFFFFF">${esc(value)}</text>
  </g>
</svg>
`;
}

/**
 * The badge set. `file` is the committed name, `truth` re-derives the value on every run.
 * Adding a badge means adding a ground-truth function — there is deliberately no way to add
 * one that carries a literal.
 */
export const BADGES = [
  { file: 'tests.svg',     label: 'tests',     truth: groundTruthTests,        valueFill: '#2E8E6E' },
  { file: 'license.svg',   label: 'license',   truth: groundTruthLicense,      valueFill: '#2E6E8E' },
  { file: 'docs.svg',      label: 'docs',      truth: groundTruthZeroDepDocs,  valueFill: '#2E6E8E' },
  { file: 'node.svg',      label: 'node',      truth: groundTruthNode,         valueFill: '#2E8E6E' },
  { file: 'any-agent.svg', label: 'any agent', truth: groundTruthAnyAgent,     valueFill: '#5C4E8E' },
];

/** Re-derive every badge and return { file, value, svg }[]. */
export function renderAll() {
  return BADGES.map((b) => {
    const value = b.truth();
    return { file: b.file, label: b.label, value, svg: drawBadge({ label: b.label, value, valueFill: b.valueFill }) };
  });
}

/**
 * The README's alt text for these badges is part of the badge, not decoration around it.
 *
 * A shield says "tests 681" in pixels and `alt="tests: 681"` in text; a screen reader gets ONLY
 * the second one. Regenerating the SVG without touching the alt would leave the two disagreeing,
 * with the readable copy the stale one — the accessible reader served the wrong number while the
 * sighted reader is served the right one. So the same ground truth owns both, and a mismatch is
 * drift exactly like a stale SVG.
 *
 * Returns a list of human-readable drift strings; empty means the page agrees with the tree.
 */
export function altTextDrift(drawn, readmeText) {
  const drift = [];
  for (const d of drawn) {
    const ref = new RegExp(`src="assets/badges/${d.file.replace(/\./g, '\\.')}"\\s+alt="([^"]*)"`);
    const m = ref.exec(readmeText);
    if (!m) continue;   // a badge the page does not show is not this check's business
    const want = `${d.label}: ${d.value}`;
    if (m[1] !== want) drift.push(`README alt for ${d.file} reads "${m[1]}", ground truth says "${want}"`);
  }
  return drift;
}

function main() {
  const check = process.argv.includes('--check');
  const drawn = renderAll();

  const readmeText = read('README.md');

  if (!check) {
    mkdirSync(badgeDir, { recursive: true });
    for (const d of drawn) {
      writeFileSync(path.join(badgeDir, d.file), d.svg);
      console.log(`gen-badges: wrote assets/badges/${d.file}  (${d.label}: ${d.value})`);
    }
    console.log(`gen-badges: ${drawn.length} badge(s) re-derived from ground truth.`);
    // The SVG bytes are ours to rewrite; the README's alt text is prose around an image and
    // is left to the author — but never left WRONG in silence.
    const altDrift = altTextDrift(drawn, readmeText);
    if (altDrift.length) {
      console.error(`\ngen-badges: README alt text is now stale in ${altDrift.length} place(s):`);
      for (const d of altDrift) console.error(`  - ${d}`);
      console.error('\nUpdate the alt attributes in README.md — a screen reader is served the alt, not the pixels.');
      process.exit(1);
    }
    process.exit(0);
  }

  const drift = [];
  for (const d of drawn) {
    const p = path.join(badgeDir, d.file);
    if (!existsSync(p)) {
      drift.push(`assets/badges/${d.file} is missing (ground truth says ${d.label}: ${d.value})`);
      continue;
    }
    if (readFileSync(p, 'utf8') !== d.svg) {
      drift.push(`assets/badges/${d.file} no longer matches ground truth (${d.label}: ${d.value})`);
    }
  }
  drift.push(...altTextDrift(drawn, readmeText));

  if (drift.length === 0) {
    console.log(`gen-badges: PASS — all ${drawn.length} badge(s) match ground truth.`);
    for (const d of drawn) console.log(`  ${d.label.padEnd(10)} ${d.value}`);
    process.exit(0);
  }
  console.error(`\ngen-badges: FAIL — ${drift.length} badge(s) drifted from the tree.`);
  for (const d of drift) console.error(`  - ${d}`);
  console.error('\nThe BADGE is stale, not the tree — re-run `node scripts/gen-badges.mjs`.');
  process.exit(1);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
